Add: User Feedback assets
getsentry/dreamy-components pull request #21
Opened 2019-08-28 20:31 UTC by jmanhart

![Screen Recording 2019-08-29 at 01 21 PM](https://user-images.githubusercontent.com/4982985/63966339-a70f9c00-ca60-11e9-87b8-d6f8e9d11787.gif)

Adding in the assets for the user feedback empty state.

2019-08-28 21:53 UTC, Chrissy requested changes
code looks great! can't wait to see the designs

2019-08-28 21:53 UTC, Chrissy commented on storybook-static/index.html
> +<!doctype html><html><head><meta charset="utf-8"><title>Storybook</title><meta name="viewport" content="width=device-width,initial-scale=1"><style>html, body {
Can we figure out where this file came from and if we need it?

2019-08-28 21:53 UTC, Chrissy commented on storybook-static/sb_dll/storybook_ui_dll.LICENCE
> +/**!
Same here

2019-08-28 21:53 UTC, Chrissy commented on yarn.lock
> -gulp-concat@^2.6.1:
this is good—let's keep this.

2019-08-28 21:53 UTC, Chrissy commented on styles/user-feedback.css
> +
so much whitespace lol

2019-08-29 18:08 UTC, Chrissy approved these changes
post a screenshot to the description I wanna see it!!!

2019-08-29 18:36 UTC, merged

2019-08-29 19:04 UTC, maheskett commented
Hm do you know why the fire emoji colors look muted here compared to figma? Also, @Chrissy do we need to bump the version to have access in sentry?

2019-08-29 19:16 UTC, Chrissy commented
I just assumed that was the screenshot tool. @jmanhart can you verify if that is happening in dev?

and yeah, thank you for reminding me. we should bump the version to 2.0.1.

2019-08-29 21:39 UTC, jmanhart commented
@Chrissy The flames appear muted in my build as well. I updated the Figma file to have no flames now and it should all be better now.